name: CI for Shashi Project

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Adjust the Python version as necessary

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip list  # List installed packages for debugging

      - name: Run tests
        run: |
          chmod +x project/test.sh  # Ensure test.sh is executable
          ./project/test.sh
