name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Python Set up 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Verify Python Version
      run: python --version

    - name: Install Libraries
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        chmod +x ./project/test.sh
        ./project/test.sh
